"""add strategy_signals

Revision ID: 0358d242b487
Revises: 895a1023f058
Create Date: 2025-12-14 01:55:41.074539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0358d242b487'
down_revision: Union[str, Sequence[str], None] = '895a1023f058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(), nullable=True),
    sa.Column('flight_key', sa.String(), nullable=True),
    sa.Column('signal_category', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('supporting_change_ids', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signals_airline'), 'strategy_signals', ['airline'], unique=False)
    op.create_index(op.f('ix_strategy_signals_detected_at'), 'strategy_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_flight_key'), 'strategy_signals', ['flight_key'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_category'), 'strategy_signals', ['signal_category'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_type'), 'strategy_signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signals_signal_type'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_category'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_flight_key'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_detected_at'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_airline'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    # ### end Alembic commands ###
