"""add price and seat fields

Revision ID: 6fb403032f1c
Revises: e7b99a7cbde0
Create Date: 2025-12-15 16:21:32.312622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fb403032f1c'
down_revision: Union[str, Sequence[str], None] = 'e7b99a7cbde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('price_total_bdt', sa.Float(), nullable=True))
    op.add_column('flight_offers', sa.Column('seat_available', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_flight_offer_identity'), 'flight_offers', type_='unique')
    op.create_unique_constraint('uq_flight_offer_identity', 'flight_offers', ['airline', 'origin', 'destination', 'departure', 'cabin', 'flight_number', 'price_total_bdt', 'seat_available'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flight_offer_identity', 'flight_offers', type_='unique')
    op.create_unique_constraint(op.f('uq_flight_offer_identity'), 'flight_offers', ['airline', 'origin', 'destination', 'departure', 'cabin', 'flight_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('flight_offers', 'seat_available')
    op.drop_column('flight_offers', 'price_total_bdt')
    # ### end Alembic commands ###
