"""add price and seat fields

Revision ID: 6fb403032f1c
Revises: e7b99a7cbde0
Create Date: 2025-12-15 16:21:32.312622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fb403032f1c'
down_revision: Union[str, Sequence[str], None] = 'e7b99a7cbde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signals_airline'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_detected_at'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_flight_key'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_category'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_type'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.add_column('flight_offers', sa.Column('price_total_bdt', sa.Float(), nullable=True))
    op.add_column('flight_offers', sa.Column('seat_available', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_flight_offer_identity'), 'flight_offers', type_='unique')
    op.create_unique_constraint('uq_flight_offer_identity', 'flight_offers', ['airline', 'origin', 'destination', 'departure', 'cabin', 'flight_number', 'price_total_bdt', 'seat_available'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_flight_offer_identity', 'flight_offers', type_='unique')
    op.create_unique_constraint(op.f('uq_flight_offer_identity'), 'flight_offers', ['airline', 'origin', 'destination', 'departure', 'cabin', 'flight_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('flight_offers', 'seat_available')
    op.drop_column('flight_offers', 'price_total_bdt')
    op.create_table('strategy_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flight_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signal_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('supporting_change_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_signals_pkey'))
    )
    op.create_index(op.f('ix_strategy_signals_signal_type'), 'strategy_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_category'), 'strategy_signals', ['signal_category'], unique=False)
    op.create_index(op.f('ix_strategy_signals_flight_key'), 'strategy_signals', ['flight_key'], unique=False)
    op.create_index(op.f('ix_strategy_signals_detected_at'), 'strategy_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_airline'), 'strategy_signals', ['airline'], unique=False)
    # ### end Alembic commands ###
