"""add flight_key to flight_offers

Revision ID: 7d4beb8c0665
Revises: d68774d073b7
Create Date: 2025-12-14 10:42:32.290085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d4beb8c0665'
down_revision: Union[str, Sequence[str], None] = 'd68774d073b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('flight_key', sa.String(), nullable=False))
    op.create_index(op.f('ix_flight_offers_flight_key'), 'flight_offers', ['flight_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_offers_flight_key'), table_name='flight_offers')
    op.drop_column('flight_offers', 'flight_key')
    # ### end Alembic commands ###
