"""add flight_offers and change_events

Revision ID: 895a1023f058
Revises: dd8ade58d649
Create Date: 2025-12-14 01:46:18.517522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '895a1023f058'
down_revision: Union[str, Sequence[str], None] = 'dd8ade58d649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(), nullable=True),
    sa.Column('flight_key', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('change_magnitude', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_airline'), 'change_events', ['airline'], unique=False)
    op.create_index(op.f('ix_change_events_change_type'), 'change_events', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_events_flight_key'), 'change_events', ['flight_key'], unique=False)
    op.create_index(op.f('ix_change_events_observed_at'), 'change_events', ['observed_at'], unique=False)
    op.add_column('flight_offers', sa.Column('operating_flight', sa.String(), nullable=True))
    op.add_column('flight_offers', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('flight_offers', sa.Column('base_price', sa.Float(), nullable=True))
    op.add_column('flight_offers', sa.Column('taxes', sa.Float(), nullable=True))
    op.add_column('flight_offers', sa.Column('aircraft_type', sa.String(), nullable=True))
    op.add_column('flight_offers', sa.Column('raw_payload', sa.JSON(), nullable=True))
    op.alter_column('flight_offers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flight_offers', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index('ix_flight_offer_route', 'flight_offers', ['origin', 'destination'], unique=False)
    op.drop_column('flight_offers', 'operating_airline')
    op.drop_column('flight_offers', 'raw_offer')
    op.drop_column('flight_offers', 'currency')
    op.drop_column('flight_offers', 'soldout')
    op.drop_column('flight_offers', 'tax_amount')
    op.drop_column('flight_offers', 'operating_flight_number')
    op.drop_column('flight_offers', 'brand')
    op.drop_column('flight_offers', 'fare_amount')
    op.drop_column('flight_offers', 'tax_components')
    op.drop_column('flight_offers', 'seat_capacity')
    op.drop_column('flight_offers', 'estimated_load_factor_pct')
    op.drop_column('flight_offers', 'baggage')
    op.drop_column('flight_offers', 'total_amount')
    op.drop_column('flight_offers', 'equipment_code')
    op.drop_column('flight_offers', 'aircraft')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('aircraft', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('equipment_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('baggage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('estimated_load_factor_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('seat_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('tax_components', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('fare_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('operating_flight_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('soldout', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('raw_offer', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('operating_airline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_flight_offer_route', table_name='flight_offers')
    op.alter_column('flight_offers', 'scraped_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('flight_offers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('flight_offers', 'raw_payload')
    op.drop_column('flight_offers', 'aircraft_type')
    op.drop_column('flight_offers', 'taxes')
    op.drop_column('flight_offers', 'base_price')
    op.drop_column('flight_offers', 'total_price')
    op.drop_column('flight_offers', 'operating_flight')
    op.drop_index(op.f('ix_change_events_observed_at'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_flight_key'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_change_type'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_airline'), table_name='change_events')
    op.drop_table('change_events')
    # ### end Alembic commands ###
