"""add brand to flight_offers

Revision ID: ae171fc16ab5
Revises: 7d4beb8c0665
Create Date: 2025-12-14 12:26:37.005035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae171fc16ab5'
down_revision: Union[str, Sequence[str], None] = '7d4beb8c0665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signals_airline'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_detected_at'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_flight_key'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_category'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_signal_type'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.add_column('flight_offers', sa.Column('brand', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_flight_offers_flight_key'), table_name='flight_offers')
    op.create_index(op.f('ix_flight_offers_departure'), 'flight_offers', ['departure'], unique=False)
    op.create_unique_constraint('uq_flight_offer_identity', 'flight_offers', ['airline', 'origin', 'destination', 'departure', 'cabin', 'flight_number'])
    op.drop_column('flight_offers', 'flight_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('flight_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_flight_offer_identity', 'flight_offers', type_='unique')
    op.drop_index(op.f('ix_flight_offers_departure'), table_name='flight_offers')
    op.create_index(op.f('ix_flight_offers_flight_key'), 'flight_offers', ['flight_key'], unique=False)
    op.drop_column('flight_offers', 'brand')
    op.create_table('strategy_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('airline', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('flight_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signal_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('supporting_change_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_signals_pkey'))
    )
    op.create_index(op.f('ix_strategy_signals_signal_type'), 'strategy_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_strategy_signals_signal_category'), 'strategy_signals', ['signal_category'], unique=False)
    op.create_index(op.f('ix_strategy_signals_flight_key'), 'strategy_signals', ['flight_key'], unique=False)
    op.create_index(op.f('ix_strategy_signals_detected_at'), 'strategy_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_airline'), 'strategy_signals', ['airline'], unique=False)
    # ### end Alembic commands ###
