"""add brand to flight_offers

Revision ID: ae171fc16ab5
Revises: 7d4beb8c0665
Create Date: 2025-12-14 12:26:37.005035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae171fc16ab5'
down_revision: Union[str, Sequence[str], None] = '7d4beb8c0665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('brand', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_flight_offers_flight_key'), table_name='flight_offers')
    op.create_index(op.f('ix_flight_offers_departure'), 'flight_offers', ['departure'], unique=False)
    op.create_unique_constraint('uq_flight_offer_identity', 'flight_offers', ['airline', 'origin', 'destination', 'departure', 'cabin', 'flight_number'])
    op.drop_column('flight_offers', 'flight_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('flight_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_flight_offer_identity', 'flight_offers', type_='unique')
    op.drop_index(op.f('ix_flight_offers_departure'), table_name='flight_offers')
    op.create_index(op.f('ix_flight_offers_flight_key'), 'flight_offers', ['flight_key'], unique=False)
    op.drop_column('flight_offers', 'brand')
    # ### end Alembic commands ###
