"""add fare and seats to flight_offers

Revision ID: ce8cc3cd3452
Revises: 6fb403032f1c
Create Date: 2025-12-17 02:02:11.147703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8cc3cd3452'
down_revision: Union[str, Sequence[str], None] = '6fb403032f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('fare_bdt', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_offers', 'fare_bdt')
    # ### end Alembic commands ###
