"""add change_events table

Revision ID: d68774d073b7
Revises: 0358d242b487
Create Date: 2025-12-14 03:35:41.824489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd68774d073b7'
down_revision: Union[str, Sequence[str], None] = '0358d242b487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_events', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('velocity', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('magnitude', sa.Float(), nullable=True))
    op.add_column('change_events', sa.Column('percent_change', sa.Float(), nullable=True))
    op.add_column('change_events', sa.Column('flight_number', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('origin', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('destination', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('cabin', sa.String(), nullable=True))
    op.add_column('change_events', sa.Column('departure', sa.DateTime(), nullable=True))
    op.add_column('change_events', sa.Column('from_timestamp', sa.DateTime(), nullable=True))
    op.add_column('change_events', sa.Column('to_timestamp', sa.DateTime(), nullable=True))
    op.add_column('change_events', sa.Column('meta', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_change_events_change_type'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_flight_key'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_observed_at'), table_name='change_events')
    op.create_index(op.f('ix_change_events_destination'), 'change_events', ['destination'], unique=False)
    op.create_index(op.f('ix_change_events_domain'), 'change_events', ['domain'], unique=False)
    op.create_index(op.f('ix_change_events_origin'), 'change_events', ['origin'], unique=False)
    op.drop_column('change_events', 'change_magnitude')
    op.drop_column('change_events', 'flight_key')
    op.drop_column('change_events', 'previous_value')
    op.drop_column('change_events', 'new_value')
    op.drop_column('change_events', 'observed_at')
    op.drop_column('change_events', 'context')
    op.add_column('flight_offers', sa.Column('price_total', sa.Float(), nullable=True))
    op.add_column('flight_offers', sa.Column('seats_available', sa.Integer(), nullable=True))
    op.alter_column('flight_offers', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_flight_offer_route'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_departure'), table_name='flight_offers')
    op.drop_column('flight_offers', 'booking_class')
    op.drop_column('flight_offers', 'total_price')
    op.drop_column('flight_offers', 'taxes')
    op.drop_column('flight_offers', 'raw_payload')
    op.drop_column('flight_offers', 'fare_basis')
    op.drop_column('flight_offers', 'arrival')
    op.drop_column('flight_offers', 'operating_flight')
    op.drop_column('flight_offers', 'base_price')
    op.drop_column('flight_offers', 'seats_remaining')
    op.drop_column('flight_offers', 'aircraft_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_offers', sa.Column('aircraft_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('seats_remaining', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('base_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('operating_flight', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('arrival', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('fare_basis', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('taxes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('flight_offers', sa.Column('booking_class', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_flight_offers_departure'), 'flight_offers', ['departure'], unique=False)
    op.create_index(op.f('ix_flight_offer_route'), 'flight_offers', ['origin', 'destination'], unique=False)
    op.alter_column('flight_offers', 'scraped_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('flight_offers', 'seats_available')
    op.drop_column('flight_offers', 'price_total')
    op.add_column('change_events', sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('change_events', sa.Column('observed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('change_events', sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('change_events', sa.Column('previous_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('change_events', sa.Column('flight_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('change_events', sa.Column('change_magnitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_change_events_origin'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_domain'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_destination'), table_name='change_events')
    op.create_index(op.f('ix_change_events_observed_at'), 'change_events', ['observed_at'], unique=False)
    op.create_index(op.f('ix_change_events_flight_key'), 'change_events', ['flight_key'], unique=False)
    op.create_index(op.f('ix_change_events_change_type'), 'change_events', ['change_type'], unique=False)
    op.drop_column('change_events', 'meta')
    op.drop_column('change_events', 'to_timestamp')
    op.drop_column('change_events', 'from_timestamp')
    op.drop_column('change_events', 'departure')
    op.drop_column('change_events', 'cabin')
    op.drop_column('change_events', 'destination')
    op.drop_column('change_events', 'origin')
    op.drop_column('change_events', 'flight_number')
    op.drop_column('change_events', 'percent_change')
    op.drop_column('change_events', 'magnitude')
    op.drop_column('change_events', 'velocity')
    op.drop_column('change_events', 'direction')
    op.drop_column('change_events', 'domain')
    # ### end Alembic commands ###
