"""initial schema

Revision ID: dd8ade58d649
Revises: 
Create Date: 2025-12-13 01:46:07.184544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8ade58d649'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_offers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('airline', sa.String(), nullable=True),
    sa.Column('operating_airline', sa.String(), nullable=True),
    sa.Column('flight_number', sa.String(), nullable=True),
    sa.Column('operating_flight_number', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('departure', sa.DateTime(), nullable=True),
    sa.Column('arrival', sa.DateTime(), nullable=True),
    sa.Column('cabin', sa.String(), nullable=True),
    sa.Column('booking_class', sa.String(), nullable=True),
    sa.Column('fare_basis', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('soldout', sa.Boolean(), nullable=True),
    sa.Column('equipment_code', sa.String(), nullable=True),
    sa.Column('aircraft', sa.String(), nullable=True),
    sa.Column('seat_capacity', sa.Integer(), nullable=True),
    sa.Column('seats_remaining', sa.Integer(), nullable=True),
    sa.Column('estimated_load_factor_pct', sa.Float(), nullable=True),
    sa.Column('fare_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('tax_components', sa.JSON(), nullable=True),
    sa.Column('baggage', sa.String(), nullable=True),
    sa.Column('raw_offer', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_offers_airline'), 'flight_offers', ['airline'], unique=False)
    op.create_index(op.f('ix_flight_offers_departure'), 'flight_offers', ['departure'], unique=False)
    op.create_index(op.f('ix_flight_offers_destination'), 'flight_offers', ['destination'], unique=False)
    op.create_index(op.f('ix_flight_offers_origin'), 'flight_offers', ['origin'], unique=False)
    op.create_index(op.f('ix_flight_offers_scraped_at'), 'flight_offers', ['scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_offers_scraped_at'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_origin'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_destination'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_departure'), table_name='flight_offers')
    op.drop_index(op.f('ix_flight_offers_airline'), table_name='flight_offers')
    op.drop_table('flight_offers')
    # ### end Alembic commands ###
