from enum import Enum


class AlertType(str, Enum):
    PRICE_SURGE = "PRICE_SURGE"
    PRICE_DROP = "PRICE_DROP"
    CAPACITY_TIGHTENING = "CAPACITY_TIGHTENING"
    DEMAND_SURGE = "DEMAND_SURGE"
    DEMAND_SOFTENING = "DEMAND_SOFTENING"
    YIELD_PROTECTION = "YIELD_PROTECTION"
    MARKET_TESTING = "MARKET_TESTING"
