from enum import Enum


class StrategySignalType(str, Enum):
    RM_TIGHTENING = "RM_TIGHTENING"
    DEMAND_ACCELERATION = "DEMAND_ACCELERATION"
    LOAD_FACTOR_PUSH = "LOAD_FACTOR_PUSH"
    MARKET_DOMINANCE = "MARKET_DOMINANCE"
    PRICE_DISCOVERY = "PRICE_DISCOVERY"
    DEFENSIVE_PRICING = "DEFENSIVE_PRICING"
    CAPACITY_WITHDRAWAL = "CAPACITY_WITHDRAWAL"
